# WhiteWash

## Using Python's List
First version using Python's list. Note that because of _aliasing_, the general way of copying a 2D list correctly is to use `deepcopy` from `copy` module, otherwise you will change the original color map rather than the new one:

In [127]:
import copy

def WhiteWash(ColorMap):
    """white wash color map as a Pyhton's list"""
    r = copy.deepcopy(ColorMap)
    for c in r:
        for i in range(3):
            c[i] += 1.0
            c[i] *= 0.5
    return r

# testing our function
cm = [[0, 0, 0], [0.1, 0.1, 0.1], [0.5, 0.5, 0.5], [1, 1, 1]]
print("before:", cm)
print("after: ", WhiteWash(cm))

before: [[0, 0, 0], [0.1, 0.1, 0.1], [0.5, 0.5, 0.5], [1, 1, 1]]
after:  [[0.5, 0.5, 0.5], [0.55, 0.55, 0.55], [0.75, 0.75, 0.75], [1.0, 1.0, 1.0]]


## Using `NumPy`'s Arrays

In [89]:
import numpy as np

def NpWhiteWash(ColorMap):
    """white wash color map as a numpy's array"""
    r =  np.ones_like(ColorMap)
    r += ColorMap
    r *= 0.5
    return r

In [128]:
cm = np.random.random(30).reshape((10, 3))

# both functions should return the same result
assert (WhiteWash(cm) == NpWhiteWash(cm)).all()

print("before white wash:")
print(cm)
print("\nafter white wash:")
print(WhiteWash(cm))
print("\nafter white wash with numpy:")
print(NpWhiteWash(cm))

before white wash:
[[ 0.3693671   0.06834142  0.235066  ]
 [ 0.5078298   0.26719496  0.27624502]
 [ 0.3195595   0.65966793  0.29023593]
 [ 0.38680201  0.05843944  0.78120633]
 [ 0.98490823  0.5648239   0.71681058]
 [ 0.3943041   0.40318016  0.96016946]
 [ 0.36586212  0.5520173   0.74783541]
 [ 0.37417918  0.39398053  0.47782891]
 [ 0.78383372  0.20435043  0.414986  ]
 [ 0.60820456  0.86983325  0.42477988]]

after white wash:
[[ 0.68468355  0.53417071  0.617533  ]
 [ 0.7539149   0.63359748  0.63812251]
 [ 0.65977975  0.82983396  0.64511797]
 [ 0.69340101  0.52921972  0.89060316]
 [ 0.99245411  0.78241195  0.85840529]
 [ 0.69715205  0.70159008  0.98008473]
 [ 0.68293106  0.77600865  0.87391771]
 [ 0.68708959  0.69699026  0.73891446]
 [ 0.89191686  0.60217522  0.707493  ]
 [ 0.80410228  0.93491662  0.71238994]]

after white wash with numpy:
[[ 0.68468355  0.53417071  0.617533  ]
 [ 0.7539149   0.63359748  0.63812251]
 [ 0.65977975  0.82983396  0.64511797]
 [ 0.69340101  0.52921972  0.8906